### ISSUE TITLE
Error: Cannot merge json objects

### ISSUE THREAD

**Issue by caifti** [indigo-dc/oidc-agent#300] opened 2020-12-07 15:50 UTC
Hi,

I've just instaleld the last verion of oidc.agent, 4.0.1, and i've a new error when trying to add a new account:
$ oidc-gen --flow device dodas
[...]
Issuer [https://iam-test.indigo-datacloud.eu/]: https://dodas-iam.cloud.cnaf.infn.it/
The following scopes are supported: openid profile email address phone offline_access eduperson_scoped_affiliation eduperson_entitlement
Scopes or 'max' (space separated) [openid profile offline_access]: max
Registering Client ...
[...]
Using a browser on another device, visit:
https://dodas-iam.cloud.cnaf.infn.it/device

And enter the code: HT........
sh: qrencode: command not found
Error: Cannot merge json objects
Only saving the account configuration. You might want to save the following content to another location.

{
	"client_id":.....
	"client_secret":	"...",
	"client_secret_expires_at":	0,
	"client_id_issued_at":	1607347279,
	"registration_access_token":	"...",
	"registration_client_uri":	"https://dodas-iam.cloud.cnaf.infn.it/register/...",
	"redirect_uris":	["edu.kit.data.oidc-agent:/redirect", "http://localhost:44044", "http://localhost:8080", "http://localhost:4242"],
	"client_name":	"oidc-agent:dodas-im-dodas.novalocal",
	"token_endpoint_auth_method":	"client_secret_basic",
	"scope":	"address phone openid profile offline_access eduperson_scoped_affiliation email eduperson_entitlement",
	"grant_types":	["urn:ietf:params:oauth:grant-type:device_code", "refresh_token"],
	"response_types":	["token"],
	"application_type":	"web",
	"name":	"dodas",
	"issuer_url":	"https://dodas-iam.cloud.cnaf.infn.it/",
	"device_authorization_endpoint":	"",
	"daeSetByUser":	....,
	"refresh_token":	"",
	"cert_path":	"/etc/pki/tls/certs/ca-bundle.crt",
	"audience":	""
}

What does it mean this error?

**Comment by zachmann** [comment] 2020-12-08 10:07
Hi Christina,

unfortunately I could not reproduce the error on indigo iam. I can try debugging the problem with dodas iam, but I don't have an account there yet. So I can continue the investigation when it gets approved.

Some background information on the error:
- When calling oidc-gen this way with a provider like iam that supports dynamic client registration, oidc-agent registers a new oidc client. This is the first step. The config (including credentials) of that client are temporarily stored in the agent. This is useful in case the following step where the user authorizes the client fails. In that case the registered client can be reused on the next try.
- Then the agent initiates the device flow using the just registered client. After successful authentication and authorization the agent receives the refresh token from the provider and creates the agent account configuration.
- oidc-gen tries to merge the agent account configuration with the client configuration. Usually this works fine. This was not the case with this issue. oidc-gen did only save the account configuration. (This is enough for the agent to work, so it should work as usual). The client configuration could not be merged and could therefore not be saved in the same file. It was printed to screen and can be saved separately. If the client configuration is not saved oidc-agent still works as expected. However, it cannot edit the client configuration (currently also not implemented) and not automatically delete the client when deleting the agent account configuration.

I hope this explanation gives some understandable context. If anything is left unclear don't hesitate to ask.

Two additional notes:
- I suggest the save the client configuration (if you still have access to it) the following way: Place it in a file located in your oidcagent directory (usually `~./config/oidc-agent`). The filename should end with `.clientconfig`, e.g. `dodas.clientconfig`. You can encrypt it by running `oidc-gen -u dodas.clientconfig`. Alternatively you can merge it manually, replacing the content of the account config file and reencrypting it with the `oidc-gen -u` command. For some information on that see the next point.
- You can help me debugging the cause of the conflict by doing the following (you also have to do this if you want to merge manually):
  - Get the decrypted account configuration: `oidc-gen -p <shortname>`
  - Compare it with the client configuration you have.
  - Report any differences. However the following should not matter:
     - keys that are present in one, but not the other
     - keys that have an empty string value in one, but not the other
     - different scope values

**Comment by caifti** [comment] 2020-12-08 13:05
"dodas iam, but I don't have an account there yet. So I can continue the investigation when it gets approved."
approved!
I confirm that the agent works, for what I used it :), as expected, dispite the error.
Thank you very much for the detailed information.
I'll try to do as you suggest and report back.

**Comment by caifti** [comment] 2020-12-08 13:16
The same way as above, I put bellow the account config decrypted:
{
	"name":	"dodas",
	"client_name":	"oidc-agent:dodas-im-dodas.novalocal",
	"issuer_url":	"https://dodas-iam.cloud.cnaf.infn.it/",
	"device_authorization_endpoint":	"https://dodas-iam.cloud.cnaf.infn.it/devicecode",
	"daeSetByUser":	.....,
	"client_id":	".....",
	"client_secret":	"......",
	"refresh_token":	".......",
	"cert_path":	"/etc/pki/tls/certs/ca-bundle.crt",
	"scope":	"address phone openid profile offline_access eduperson_scoped_affiliation email eduperson_entitlement",
	"audience":	"",
	"redirect_uris":	["edu.kit.data.oidc-agent:/redirect", "http://localhost:44044", "http://localhost:8080", "http://localhost:4242"],
	"username":	"",
	"password":	""
}
client_id and client_secret are the same in both files.
daeSetByUser are different between the 2 files

Hope it helps

**Comment by zachmann** [comment] 2020-12-08 13:26
Thanks, that helps indeed. The problem is indeed the daeSetByUser. This is set when using the `--dae` command line option. I assume you did this even though I could not find it above. Note that this option is not (no longer) needed with iam.
When I include the `--dae` option on the oidc-gen call, I can reproduce the error.
I'll fix this.

**Comment by caifti** [comment] 2020-12-08 15:10
hmmm, in fact I didn't used the "--dae"
The command I used is the one I've post: "oidc-gen --flow device dodas"

**Closed** 2020-12-09 13:01 UTC
Labels: bug, oidc-gen
