### ISSUE TITLE
inconsisten FHS paths in oidc-agent-service

### ISSUE THREAD

**Issue by thdesy** [indigo-dc/oidc-agent#491] opened 2023-03-17 11:17 UTC
Hi,

in oidc-agent [1] the path to itself seems to be broken (looks like concatenated /bin with /usr/bin) 

```
OIDC_AGENT="${OIDC_AGENT:-/usr/bin/bin/oidc-agent}"
```

which clashes when calling the agent per eval
```
> eval `oidc-agent-service use`
/bin/oidc-agent-service: line 77: /usr/bin/bin/oidc-agent: No such file or directory
```

there seem to be a few helper paths hard wired, which might be risky for `/bin`  (should not really a problem with most RH based distros symlinking /bin to /usr/bin)

```
JQ=jq
CAT=/bin/cat
ECHO=/bin/echo
LN=/bin/ln
RM=/bin/rm
MKDIR=/bin/mkdir
REALPATH=realpath
```

Cheers,
  Thomas

[1]
```
oidc-agent-cli-4.5.1-1.el7.x86_64
oidc-agent-4.5.1-1.el7.x86_64
oidc-agent-desktop-4.5.1-1.el7.x86_64
liboidc-agent4-4.5.1-1.el7.x86_64
```

**Comment by marcvs** [comment] 2023-03-17 12:57
Most likely this is a dupe of #490  I'll check it next week.

**Comment by marcvs** [comment] 2023-03-29 02:42
duplicate of #490

**Closed by marcvs** 2023-03-29 02:42 UTC
