### ISSUE TITLE
oidc-token returns success even if the account name is unknown

### ISSUE THREAD

**Issue by paulmillar** [indigo-dc/oidc-agent#284] opened 2020-10-01 14:33 UTC
```
paul@celebrimbor:~$ oidc-token FOO
Error: No account configured with that short name
paul@celebrimbor:~$ echo $?
0
paul@celebrimbor:~$ 
```

I would expect `oidc-token` to return a non-zero return code if the short name is unknown.

**Comment by zachmann** [comment] 2020-10-01 14:57
Duplicate of #280 
This behavior will be fixed in version 4.0.0

**Closed** 2020-10-01 14:58 UTC
Labels: duplicate
