### ISSUE TITLE
Add mechanism to specify desired `aud`

### ISSUE THREAD

**Issue by bbockelm** [indigo-dc/oidc-agent#233] opened 2019-12-26 20:08 UTC
We often use the `aud` claim to control where an otherwise-generic token is applicable.  For IAM, we this is done via the `audience` token request parameter (as registered with [IANA](https://www.iana.org/assignments/oauth-parameters/oauth-parameters.xhtml) as part of the [token exchange draft RFC](https://datatracker.ietf.org/doc/draft-ietf-oauth-token-exchange/)).

Unfortunately, this functionality is not exposed in `oidc-agent`.  Is it possible to add the ability to specify a desired token audience as part of an account that is setup in an invocation of `oidc-gen`?

**Comment by bbockelm** [comment] 2020-01-08 02:03
Any thoughts on this?  I'm starting to come back from holidays myself and am thinking about this topic again...

**Comment by zachmann** [comment] 2020-01-09 06:42
I'm sorry for the delayed response. I got sick right after my vacation.
I agree with you that such a mechanism is useful and I already thought about it myself. Unfortunately I could not find a provider that currently supports requesting a specific audience (outside of token exchange) and sets it in the access token. It would be helpful if you can point me to one I can use for testing.
I also wasn't sure how the audience can be requested with the provider and it seems that there are different approaches.
You suggested the `audience` request parameter following the token exchange draft. This seems reasonable to me and more suitable than the `resource` parameter. However there is also a draft about [using JWTs as ATs](https://tools.ietf.org/html/draft-ietf-oauth-access-token-jwt-03#section-3) that uses the `resource` parameter.

It would be helpful to have a standardized way for requesting a specific audience and I think  that the draft about JWTs as ATs would be a good place for this. However, it also seems that this draft that not allow multiple audiences (only aliases), which I think would be useful.

So if you can point me to a provider I can test this with, I will implement this feature.

**Comment by andreaceccanti** [comment] 2020-01-09 09:39
HI @zachmann ,
IAM supports requesting the audience, so you can use it!

**Comment by andreaceccanti** [comment] 2020-01-09 09:44
In particular, if an "audience" request parameter is included in token requests IAM will use such audience in the issued token. The "audience" request parameter is a space-separeted list of strings. If a single value is provided, the token will have a single-valued string aud claim containing such value. If multiple values are provided, the token will have a multi-valued string array aud claim.

**Comment by zachmann** [comment] 2020-01-09 10:02
@andreaceccanti that's nice to hear. 
Can you confirm that the IAM version deployed to 
- iam-test.indigo-datacloud.eu
- iam.deep-hybrid-datacloud.eu

support this?

I think I did test this in the past. I also just tested it with iam-test and could not get it to work using the refresh flow.
I assumed that iam does not support this, since no AT I obtain from iam contains the `aud` claim.

I used the following curl call to request the AT:
```
curl -X POST ${ISS}token -u $CID:$CS -d "grant_type=refresh_token&refresh_token=${RT}&audience=${CID}"
```

**Comment by andreaceccanti** [comment] 2020-01-09 18:23
@zachmann iam-test supports it, but you found the only grant type that currently does not support the audience parameter (refresh token, and I still have to sort out whether this is a bug or the right behaviour).

audience is supported on the device code, password, authz code and token exchange.
audience is maintained across a refresh.

**Comment by zachmann** [comment] 2020-01-10 06:31
I just tested it with the authorization code flow, but still no audience in the AT. However, I might have to test this more lengthy.

> I still have to sort out whether this is a bug or the right behaviour
I vote for enabling requesting the audience on the refresh grant type. I would suggest audience is maintained across a refresh if no audience parameter is included in the request. If there is already an audience restriction for the initial AT/RT audience can only be restricted. If initially no audience was provided it can be restricted to any audience.

@bbockelm suggested to include the audience with `oidc-gen`; for this behavior it is not required that audience can be specified with the refresh grant type. However, I actually would like to have the audience option (additionally) with `oidc-token`: this would allow a user to use a single account configuration (with no audience set) and request AT with different audiences through `oidc-token`. However, this would require the ability to set audience when refreshing a token.

**Comment by andreaceccanti** [comment] 2020-01-10 07:08
> I just tested it with the authorization code flow, but still no audience in the AT. However, I might have to test this more lengthy.

Can you share the precise sequence of requests you tried (as curl calls)

I envision oidc-agent to be mostly used with the devide code flow, I would focus on that.
That works fine  here, using this [script][script]:

```bash
$ IAM_CLIENT_AUDIENCE=test-audience ./dc-get-access-token.sh

Please open the following URL in the browser:

https://iam-test.indigo-datacloud.eu/device?user_code=IJS9NT

and, after having been authenticated, enter the following code when requested:

IJS9NT

Note that the code above expires in 1800 seconds...
Once you have correctly authenticated and authorized this device, this script can be restarted to obtain a token.

Proceed? [Y/N] (CTRL-c to abort)
Y

An access token was issued, with the following scopes:

openid profile

which expires in 3599 seconds.
...

$ echo $IAM_ACCESS_TOKEN | jwt
✻ Header
{
  "kid": "rsa1",
  "alg": "RS256"
}

✻ Payload
{
  "sub": "e1eb758b-b73c-4761-bfff-adc793da409c",
  "aud": "test-audience",
  "iss": "https://iam-test.indigo-datacloud.eu/",
  "exp": 1578643306,
  "iat": 1578639706,
  "jti": "0e38fd49-bfbd-4486-9782-887ea7693fc2"
}
```

The audience parameter must be included in the token request.

>  If there is already an audience restriction for the initial AT/RT audience can only be restricted.

So when is an audience restricted? That could be a tricky definition. I have to understand the implications on the code base, since the basic assumptions of the refresh token flow is that
is used to refresh a token with the existing privileges. Scopes can be limited, and that's well defined. There's no standard guidance however for audience restriction behaviour (we can of course come up with something!).

[script]: https://github.com/andreaceccanti/indigo-aai-tutorial/blob/master/scripts/dc-get-access-token.sh

**Comment by zachmann** [comment] 2020-01-10 07:57
> Can you share the precise sequence of requests you tried (as curl calls)

I used the following authorization url:
```
AUTH_URL="${IAM_AUTHORIZATION_ENDPOINT}?response_type=code&client_id=${IAM_CLIENT_ID}&redirect_uri=${IAM_REDIRECT_URI}&scope=${IAM_CLIENT_SCOPES}"
```

And then used the code in this curl call:
```
 curl -L \
    -d client_id=${IAM_CLIENT_ID} \
    -d client_secret=${IAM_CLIENT_SECRET} \
    -d grant_type=authorization_code \
    -d code=${IAM_CODE} \
    -d redirect_uri=${IAM_REDIRECT_URI} \
    -d audience="${IAM_CLIENT_AUDIENCE}" \
    ${IAM_TOKEN_ENDPOINT}
```

**Comment by zachmann** [comment] 2020-01-10 08:25
> I envision oidc-agent to be mostly used with the devide code flow, I would focus on that.
That works fine

I now tested it with the device flow, which is indeed working. However, I could not get it to work with the authroization code flow.

I also think that the device flow is a nice flow. However, in the oidc-agent use case the most used flow will always be the refresh flow. Since the other flows (device, authorization code, password) are only used to obtain an RT and afterwards this RT is used to obtain additional ATs. Therefore, it would be useful to be able to set the audience when refreshing an AT.

> So when is an audience restricted? That could be a tricky definition. I have to understand the implications on the code base, since the basic assumptions of the refresh token flow is that
is used to refresh a token with the existing privileges. Scopes can be limited, and that's well defined. 

I understand your point. I would say an audience is restricted when there is an audience specified for the token. I would expect something like the following hierarchy:
```
no audience > multiple audiences (e.g. foo bar foofoo) > less audiences (e.g. foo bar) > single audience (e.g. foo)
``` 

> There's no standard guidance however for audience restriction behavior (we can of course come up with something!).

Right, AFAIK there's generally not much information about audience usage with oidc. Maybe it would make sense to write something up (@marcvs @urost). I think it would be good to have a document for that, but I don't see anyone really having time for it.

**Comment by andreaceccanti** [comment] 2020-01-10 11:58
> I understand your point. I would say an audience is restricted when there is an audience specified for the token. I would expect something like the following hierarchy:

Yes, that make sense. However an audience can be a label that identifies a logical set of resources which would require the authz server to have knowledge of the equivalence relationship among labels, which is necessarily application specific.

For the authz code you should request the audience in the _token_ request (you show an authorization request, which goes to a different endpoint).

**Comment by zachmann** [comment] 2020-01-10 13:04
> Yes, that make sense. However an audience can be a label that identifies a logical set of resources which would require the authz server to have knowledge of the equivalence relationship among labels, which is necessarily application specific.

Right, didn't had that in mind. We cannot expect the authz server to know about audience relationships. But I think it's fine if we leave this out, so that when refreshing a token for a specific audience, these values all have to be in the original audience in the same way as they are now requested (or there wasn't an audience at all before).

For oidc-agent I expect that the use case most likely will be that the inital token does not have an audience, so that any audience applied is a valid restriction.

**Comment by bbockelm** [comment] 2020-01-15 20:26
Hi @zachmann, @andreaceccanti -

Since we're having a hackathon tomorrow at CERN: if this issue comes up, what should the summary be?  Is something in progress?  Is it stuck?  Etc..

Brian

**Comment by marcvs** [comment] 2020-01-16 08:08
From my understanding this issue is being worked on, with the goal to
support it properly.

**Comment by zachmann** [comment] 2020-01-16 09:02
@bbockelm We are absolutely willing to support this!
But we still have to figure out in which way we can support it, because this depends on the support by the provider. 
At the moment I only can implement this option for `oidc-gen` and not for `oidc-token` since there's no support yet for requesting `aud` with the refresh flow. Since I could only got this to work with the device flow and not the authorization code flow, support will be limit, but I will start with this.

**Comment by andreaceccanti** [comment] 2020-01-16 10:39
Hi @zachmann,

IAM now supports limiting the audience also on the refresh token flow, if you want something to test against The WLCG IAM instance has the latest changes.

No checks on the original audience are there now.

**Comment by zachmann** [comment] 2020-01-16 14:20
Thanks, for implementing this with iam, I will work on it on my site.

**Comment by zachmann** [comment] 2020-01-17 07:20
> Hi @zachmann,
> 
> IAM now supports limiting the audience also on the refresh token flow, if you want something to test against The WLCG IAM instance has the latest changes.
> 
> No checks on the original audience are there now.

@andreaceccanti I now had the time to test this and I can confirm it works. However, when I include the audience in the refresh flow, the issued token _and all tokens issued in the future_ have the specified audience. I'd expect that the audience would only apply to this issued AT and that ATs returned on other refresh flows that don't include the audience request parameter, don't have the same audience.

I'm not sure if this is understandable so I'll do a short example:

This is what it currently is:
- Refresh flow request including `audience=foo bar` -> AT with `aud=["foo", "bar"]`
- Refresh flow request (same RT) without an audience parameter -> AT with `aud=["foo", "bar"]`

I expected:
- Refresh flow request including `audience=foo bar` -> AT with `aud=["foo", "bar"]`
- Refresh flow request (same RT) without an audience parameter -> AT without audience / general audience

So, it seems like currently including the audience request parameter changes the audience of the newly issued AT and also of the RT. For `oidc-agent` I would like to have this different.
What do you think?

**Comment by andreaceccanti** [comment] 2020-01-17 10:37
Hi @zachmann,

I will look into this ASAP.
In theory the correct behavior should be that the initial refresh token is not restricted in audience, and a possibly different audience restriction can be requested at each token request.

I will check and get back to you.

**Comment by andreaceccanti** [comment] 2020-01-17 10:44
Note however that there are scenarios in which refresh tokens are not reused, i.e. are valid for only one refresh, and in that case the audience requested will be linked to the new token pair. So basically the audience should be maintained unless overridden. Does this make sense to you?

**Comment by zachmann** [comment] 2020-01-17 10:56
Yes, I think that makes sense. It is clear that when a new refresh token is issued that it will have the new audience. If the same RT is returned, the audience should be maintained.

**Comment by zachmann** [comment] 2020-01-17 10:57
@bbockelm Implementation is basically finished, and version 3.3.0 will introduce the `--aud` option to `oidc-gen` and `oidc-token`

**Comment by andreaceccanti** [comment] 2020-01-17 15:43
@zachmann in the flow that gets you the first refresh token,  does oidc-agent include the  audience parameter? Since AFAIU, the first request shouldn't have the audience, only the refresh requests IIUC.

**Comment by bbockelm** [comment] 2020-01-17 19:09
@zachmann great!  Once there's a branch available, let me know and I'll be happy to test it out.

**Comment by andreaceccanti** [comment] 2020-01-20 10:33
HI @zachmann , you were right there was a bug in the IAM implementation. Now it works fine AFAIU. The latest code is live on the WLCG instance, let me know if it works as expected also for you.

**Comment by zachmann** [comment] 2020-01-21 08:44
> HI @zachmann , you were right there was a bug in the IAM implementation. Now it works fine AFAIU. The latest code is live on the WLCG instance, let me know if it works as expected also for you.

@andreaceccanti Great, I will check it out in the afternoon.



> @zachmann great! Once there's a branch available, let me know and I'll be happy to test it out.

@bbockelm the changes are in the [dev_3.3.0 branch](https://github.com/indigo-dc/oidc-agent/tree/dev_3.3.0)

**Comment by zachmann** [comment] 2020-01-21 14:38
> HI @zachmann , you were right there was a bug in the IAM implementation. Now it works fine AFAIU. The latest code is live on the WLCG instance, let me know if it works as expected also for you.

I now can also get an audienced AT when using the authorization code flow.
Also the audience of the refresh token does not longer seem to be changed. So this is nice.
However, I can no longer obtain an audienced AT (with the refresh flow) when the used refresh token was issued with no audience (i.e. `https://wlcg.cern.ch/jwt/v1/any`). So if I did not include the `audience` parameter in the token request of the initial authorization code flow, I won't get ATs with an audience when doing the refresh flow.

**Comment by andreaceccanti** [comment] 2020-01-23 07:42
Hi @zachmann ,

there was a bug specific to the WLCG profile, that I've now fixed, and is now live on the WLCG instance.

**Closed** 2020-01-28 13:26 UTC
Labels: API, feature, liboidc-agent, oidc-agent, oidc-token
